#  PANDAS

In [9]:
import numpy as np
import pandas as pd

In [3]:
dict1={"name":['Aniket','virat','skeel','shubh'],"marks":[97,69,45,66],"city":['UP','delhi','kanpur','punjab']}

In [6]:
df=pd.DataFrame(dict1)

In [7]:
df

     name  marks    city
0  Aniket     97      UP
1   virat     69   delhi
2   skeel     45  kanpur
3   shubh     66  punjab

In [25]:
newdata=pd.DataFrame(np.random.randint((3,2,6)))

In [26]:
newdata

   0
0  2
1  1
2  4

In [27]:
newdata.describe()

              0
count  3.000000
mean   2.333333
std    1.527525
min    1.000000
25%    1.500000
50%    2.000000
75%    3.000000
max    4.000000

In [28]:
newdata.shape

(3, 1)

In [2]:
#self work
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance', 'Finance', 'IT'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Salary': [50000, 52000, 60000, 58000, 65000, 62000, 61000],
    'Experience': [2, 3, 5, 4, 7, 6, 5]
}

df = pd.DataFrame(data)
print(df)

  Department Employee  Salary  Experience
0         HR    Alice   50000           2
1         HR      Bob   52000           3
2         IT  Charlie   60000           5
3         IT    David   58000           4
4    Finance      Eve   65000           7
5    Finance    Frank   62000           6
6         IT    Grace   61000           5

In [6]:
df.groupby(['Department', 'Experience'])['Salary'].mean()

Department  Experience
Finance     6             62000.0
            7             65000.0
HR          2             50000.0
            3             52000.0
IT          4             58000.0
            5             60500.0
Name: Salary, dtype: float64

In [10]:
df.groupby('Department').agg({
    'Salary': ['mean', 'max'],
    'Experience': ['mean', 'min']
})

                  Salary        Experience
                    mean    max       mean min
Department
Finance     63500.000000  65000   6.500000   6
HR          51000.000000  52000   2.500000   2
IT          59666.666667  61000   4.666667   4

In [11]:
df.groupby('Department').count()

            Employee  Salary  Experience
Department
Finance            2       2           2
HR                 2       2           2
IT                 3       3           3

In [12]:
df.groupby('Department')['Salary'].sum()

Department
Finance    127000
HR         102000
IT         179000
Name: Salary, dtype: int64

In [13]:
df.groupby('Department')['Salary'].max()

Department
Finance    65000
HR         52000
IT         61000
Name: Salary, dtype: int64

In [15]:
df.groupby('Department')['Salary'].mean(numeric_only=True)

Department
Finance    63500.000000
HR         51000.000000
IT         59666.666667
Name: Salary, dtype: float64